// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../modules/carrinho/domain/entities/carrinho_entity.dart';
import '../../../modules/produtos/domain/entities/produto_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 9044549204155932233),
      name: 'CarrinhoEntity',
      lastPropertyId: const obx_int.IdUid(9, 2580696495264995561),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1163446992323442912),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2382870900619339872),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7067986455860833161),
            name: 'detail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4876989607971192018),
            name: 'price',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1979706362639149012),
            name: 'hero',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8829437882615529572),
            name: 'image',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 302372564179396652),
            name: 'info',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4306342741598913555),
            name: 'offer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2580696495264995561),
            name: 'qntd',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8812162439442330648),
      name: 'ProdutoEntity',
      lastPropertyId: const obx_int.IdUid(8, 1401919271446172340),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1230389941147761709),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1801223285073267677),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 931725090034760186),
            name: 'detail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3330274649658671700),
            name: 'price',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7001828367897837024),
            name: 'hero',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6033823392731445931),
            name: 'image',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3818691883041458729),
            name: 'info',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1401919271446172340),
            name: 'offer',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 8812162439442330648),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CarrinhoEntity: obx_int.EntityDefinition<CarrinhoEntity>(
        model: _entities[0],
        toOneRelations: (CarrinhoEntity object) => [],
        toManyRelations: (CarrinhoEntity object) => {},
        getId: (CarrinhoEntity object) => object.id,
        setId: (CarrinhoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CarrinhoEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final detailOffset =
              object.detail == null ? null : fbb.writeString(object.detail!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final heroOffset =
              object.hero == null ? null : fbb.writeString(object.hero!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final infoOffset =
              object.info == null ? null : fbb.writeString(object.info!);
          final offerOffset =
              object.offer == null ? null : fbb.writeString(object.offer!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, detailOffset);
          fbb.addOffset(3, priceOffset);
          fbb.addOffset(4, heroOffset);
          fbb.addOffset(5, imageOffset);
          fbb.addOffset(6, infoOffset);
          fbb.addOffset(7, offerOffset);
          fbb.addInt64(8, object.qntd);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final detailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final priceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final heroParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final infoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final offerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final qntdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final object = CarrinhoEntity(
              id: idParam,
              name: nameParam,
              detail: detailParam,
              price: priceParam,
              hero: heroParam,
              image: imageParam,
              info: infoParam,
              offer: offerParam,
              qntd: qntdParam);

          return object;
        }),
    ProdutoEntity: obx_int.EntityDefinition<ProdutoEntity>(
        model: _entities[1],
        toOneRelations: (ProdutoEntity object) => [],
        toManyRelations: (ProdutoEntity object) => {},
        getId: (ProdutoEntity object) => object.id,
        setId: (ProdutoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ProdutoEntity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final detailOffset =
              object.detail == null ? null : fbb.writeString(object.detail!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final heroOffset =
              object.hero == null ? null : fbb.writeString(object.hero!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final infoOffset =
              object.info == null ? null : fbb.writeString(object.info!);
          final offerOffset =
              object.offer == null ? null : fbb.writeString(object.offer!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, detailOffset);
          fbb.addOffset(3, priceOffset);
          fbb.addOffset(4, heroOffset);
          fbb.addOffset(5, imageOffset);
          fbb.addOffset(6, infoOffset);
          fbb.addOffset(7, offerOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final detailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final priceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final heroParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final infoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final offerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final object = ProdutoEntity(
              id: idParam,
              name: nameParam,
              detail: detailParam,
              price: priceParam,
              hero: heroParam,
              image: imageParam,
              info: infoParam,
              offer: offerParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CarrinhoEntity] entity fields to define ObjectBox queries.
class CarrinhoEntity_ {
  /// see [CarrinhoEntity.id]
  static final id =
      obx.QueryIntegerProperty<CarrinhoEntity>(_entities[0].properties[0]);

  /// see [CarrinhoEntity.name]
  static final name =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[1]);

  /// see [CarrinhoEntity.detail]
  static final detail =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[2]);

  /// see [CarrinhoEntity.price]
  static final price =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[3]);

  /// see [CarrinhoEntity.hero]
  static final hero =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[4]);

  /// see [CarrinhoEntity.image]
  static final image =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[5]);

  /// see [CarrinhoEntity.info]
  static final info =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[6]);

  /// see [CarrinhoEntity.offer]
  static final offer =
      obx.QueryStringProperty<CarrinhoEntity>(_entities[0].properties[7]);

  /// see [CarrinhoEntity.qntd]
  static final qntd =
      obx.QueryIntegerProperty<CarrinhoEntity>(_entities[0].properties[8]);
}

/// [ProdutoEntity] entity fields to define ObjectBox queries.
class ProdutoEntity_ {
  /// see [ProdutoEntity.id]
  static final id =
      obx.QueryIntegerProperty<ProdutoEntity>(_entities[1].properties[0]);

  /// see [ProdutoEntity.name]
  static final name =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[1]);

  /// see [ProdutoEntity.detail]
  static final detail =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[2]);

  /// see [ProdutoEntity.price]
  static final price =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[3]);

  /// see [ProdutoEntity.hero]
  static final hero =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[4]);

  /// see [ProdutoEntity.image]
  static final image =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[5]);

  /// see [ProdutoEntity.info]
  static final info =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[6]);

  /// see [ProdutoEntity.offer]
  static final offer =
      obx.QueryStringProperty<ProdutoEntity>(_entities[1].properties[7]);
}
