name: produtos
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.2.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  bloc_test: ^9.1.7
  another_flushbar: ^1.12.30
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.0.0
  objectbox_generator: any


flutter:

  uses-material-design: true

  assets:
    - assets/
